### PR TITLE
Add name to js docs for behavior

### PR DESCRIPTION
**Pull request by jakemac53**
This allows hydrolysis to see the behavior name

### CODE REVIEW

**Comment by jakemac53** [comment]
fwiw the CI failure does not appear to be related to this cl

**Comment by atotic** [comment]
I'd merge, but I am curious why is this needed. When I implemented behavior parsing in hydrolysis, we had automatic behavior name detection. It should have picked this up.
Here is the automatic detection:
https://github.com/Polymer/hydrolysis/blob/master/lib/ast-utils/behavior-finder.js#L144

**Comment by jakemac53** [comment]
ah you know what you are right, after a bit more investigation my issue was actually with the difference between `Polymer.IronJsonpLibraryBehavior` and `IronJsonpLibraryBehavior`. There is some inconsistency it seems across the various elements, (some specify the name without the Polymer.*).

**Comment by goldieep** [comment]
thank you @jakemac53

**Pull request closed without merging**
